CIS_341_Fitness_App_12_8/WorkoutTrackingApp/Controllers/ExercisesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WorkoutTrackingApp.Data;
using WorkoutTrackingApp.Models;
using WorkoutTrackingApp.ViewModels;

namespace WorkoutTrackingApp.Controllers
{
    

    public class ExercisesController : Controller
    {

        private readonly WorkoutTrackingAppContext _context; // Defining the database context

        public ExercisesController(WorkoutTrackingAppContext context)
        {
            _context = context;
        }

        // [AllowAnonymous]
        public IActionResult Index()
        {
            var exercises = _context.Exercises
                                  .Select(e => new ExerciseViewModel
                                  {
                                      Id = e.ExerciseId,
                                      Name = e.Name,
                                      Description = e.Description,
                                      
                                  })
                                  .ToList();

            return View(exercises);
        }

       // [AllowAnonymous]
        public IActionResult Details()
        {
            return View();
        }

        //[Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            
            return View("ManageExercises", new ExerciseViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExerciseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var exercise = new Exercise 
                {
                    Name = model.Name,
                    Description = model.Description,
                    Intensity = model.Intensity,
                    
                };

                _context.Exercises.Add(exercise);
                _context.SaveChanges();

                
                return RedirectToAction("Index");
            }

            return View(model);
        }

       // [Authorize]
        public IActionResult Edit()
        {
            return View();
        }

        [Authorize]
        public IActionResult Delete() 
        {
            return View();
        }
    }
}

CIS_341_Fitness_App_12_8/WorkoutTrackingApp/Controllers/TrainerProfileDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WorkoutTrackingApp.ViewModels;

namespace WorkoutTrackingApp.Controllers
{
    //[Authorize]
    [AllowAnonymous]
    public class TrainerProfileDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }

        
        public IActionResult ManageWorkouts()
        {
            // This would normally come from a database or service.
            var exercises = new List<ExerciseViewModel>
        {
            // Populate with actual data
            new ExerciseViewModel { Name = "Squat", Description = "A leg exercise.", /* ... other properties ... */ },
            // ... other exercises ...
        };

            return View(exercises);
        }

      
        public IActionResult ManageExercises()
        {
            //Also will fill up with database 
            var exerciseList = new List<ExerciseViewModel>
            {
                new ExerciseViewModel
                {
                    Name = "Push-up",
                    Description = "A push-up, go in plank position and bend arms down to 90 degrees and then back up...",
                    TargetMuscleGroup = "Chest",
                    EquipmentRequired = "None",
                    Difficulty = "Begineer",
                },
            };
            return View(exerciseList);           
        }

       
        public IActionResult Subscribers()
        {
            //This will be replaced with the database when it gets created and hooked up
            var subscriberList = new List<SubscriberViewModel>
            {
                new SubscriberViewModel
                {
                    UserName = "User1",
                    SubscriptionStartDate = DateTime.Now.AddMonths(-1),
                    SubscriptionStatus = "Active",
                    NumberOfCompletedWorkouts = 15
                },          
            };
            return View(subscriberList);
        }

        
        public IActionResult PopularWorkouts()
        {
            return View();
        }
    }
}

CIS_341_Fitness_App_12_8/WorkoutTrackingApp/Views/TrainerProfileDashboard/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    Could possibly include the popular workouts in this view
    // Deleted Profile.cshtml because I figure this will be the profile
*@
@{
    <h1>This will be the TrainerDashboardPage</h1>

    <a class="btn btn-primary" asp-controller="Exercises" asp-action="Create">Create New Exercise</a>
    <a class="btn btn-primary" asp-controller="Exercises" asp-action="Create">Create New Exercise</a>
}

CIS_341_Fitness_App_12_8/WorkoutTrackingApp/Views/TrainerProfileDashboard/ManageExercises.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*<a href="@Url.Action("Create", "Exercises")" class="btn btn-primary">Create New Exercise</a>*@

CIS_341_Fitness_App_12_8/WorkoutTrackingApp/Views/TrainerProfileDashboard/ManageWorkouts.cshtml
@model IEnumerable<WorkoutTrackingApp.ViewModels.ExerciseViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Manage Exercises</h2>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Target Muscle Group</th>
            <th>Equipment Required</th>
            <th>Difficulty</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var exercise in Model)
        {
            <tr>
                <td>@exercise.Name</td>
                <td>@exercise.Description</td>
                <td>@exercise.TargetMuscleGroup</td>
                <td>@exercise.EquipmentRequired</td>
                <td>@exercise.Difficulty</td>
                <td>
                    
                    <a href="@Url.Action("Edit", "Exercises", new { id = exercise.Id })">Edit</a> |
                    <a href="@Url.Action("Details", "Exercises", new { id = exercise.Id })">Details</a> |
                    <a href="@Url.Action("Delete", "Exercises", new { id = exercise.Id })"
                       onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" href="@Url.Action("Create", "Exercises")">Add New Exercise</a>